//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.artech.com", ConfigurationName="ServiceReference1.IFoo")]
    public interface IFoo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/IFoo/Doth", ReplyAction="http://www.artech.com/IFoo/DothResponse")]
        void Doth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/IFoo/Doth", ReplyAction="http://www.artech.com/IFoo/DothResponse")]
        System.Threading.Tasks.Task DothAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFooChannel : ConsoleApplication1.ServiceReference1.IFoo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FooClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IFoo>, ConsoleApplication1.ServiceReference1.IFoo {
        
        public FooClient() {
        }
        
        public FooClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FooClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FooClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FooClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Doth() {
            base.Channel.Doth();
        }
        
        public System.Threading.Tasks.Task DothAsync() {
            return base.Channel.DothAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.artech.com", ConfigurationName="ServiceReference1.IBar")]
    public interface IBar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/IBar/Doth2", ReplyAction="http://www.artech.com/IBar/Doth2Response")]
        void Doth2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/IBar/Doth2", ReplyAction="http://www.artech.com/IBar/Doth2Response")]
        System.Threading.Tasks.Task Doth2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarChannel : ConsoleApplication1.ServiceReference1.IBar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IBar>, ConsoleApplication1.ServiceReference1.IBar {
        
        public BarClient() {
        }
        
        public BarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Doth2() {
            base.Channel.Doth2();
        }
        
        public System.Threading.Tasks.Task Doth2Async() {
            return base.Channel.Doth2Async();
        }
    }
}
